### ISSUE TITLE
no code in readme

### ISSUE THREAD

**Issue by ghost** [olov/jsshaper#1]
Showing how to do something simple and useful with jsshaper right at the top of the readme in a code block should do wonders for convincing people that this project is something they'd like to use!

Also the readme says there are examples but it's not obvious where those are located.

**Comment by olov** [comment]
The lack of documentation is a known problem so I'll leave this issue open until it has been improved. Until then the best way to get started in using Shaper is trying out one of the plugins it comes with, such as asserter, restricter or bitwiser.

**Comment by olov** [comment]
I'm closing this now. Thanks for the comment - I've kept it in mind for everything I've published on NPM.
