### ISSUE TITLE
in-Browser demo broken

### ISSUE THREAD

**Issue by JamieMason** [olov/jsshaper#8]
jsshaper/src/browser.html when run in a browser gives a 404 error for jsshaper/src/plugins/yielder/yielder.js

**Comment by olov** [comment]
Thanks for reporting. The yielder plugin hasn't been merged yet, check out @cscott's fork until we have it merged proper. The browser.html file seems to have slipped in with the AMD-ification @cscott contributed, we have some cleaning up to do.

**Comment by JamieMason** [comment]
Thanks Olov, I was led there as I saw the example folder. I'm not sure about others, but I could use a guide to how to integrate jsshaper in a browser project if possible, ideally with AMD. When I saw browser.html there, I thought that must be what I was looking for.

Really interested in this after your talk at Front Trends, just need some help with getting set up.

Thanks.

**Comment by cscott** [comment]
Yeah, I was working on AMD-ification and stalled a bit.  But it's certainly possible to integrate the yielder shaper (at least) as a one-file require.js plugin.  I just got hung up on the details on packing this up for node.

**Comment by olov** [comment]
@JamieMason that's a good suggestion, we should have that. Meanwhile feel free to check out `build/build-restricter.sh` which among other things creates `all-restricter.js` (the restricter plugin with shaper and dependencies). That file is in turn used by http://restrictmode.org/try.

Just curious, what's your use case for running Shaper in the browser?

**Comment by olov** [comment]
@cscott What's the current status of yielder? Getting ready for a merge?

**Comment by JamieMason** [comment]
@olov the js I want to apply it to is a require.js and backbone project run in the browser, I couldn't work out how to apply jsshaper to it - it's probably just me, but I could use some more docs to help me find my way.
